<?php
if ( class_exists( 'WP_Customize_Control' ) ) {
	class WP_Customize_CST_SF_Sorter_Control extends \WP_Customize_Control {

		/**
		 * Control type.
		 *
		 * @since 3.1.0
		 * @access public
		 * @var string
		 */
		public $type = 'cst_sf_sorter_control';

		/**
		 * Section Sort Order.
		 *
		 * @since 3.1.0
		 * @access public
		 * @var array
		 */
		public $sort_order = [];

		public function __construct( WP_Customize_Manager $manager, $id, array $args = [] ) {
			parent::__construct( $manager, $id, $args );
			$this->setup_actions();
		}

		public function setup_actions() {
			$this->sort_order = \CST\CST_Section_Front::get_instance()->chicago_sports_team_slugs;
			add_action( 'customize_controls_enqueue_scripts', [ $this, 'custom_control_enqueue' ] );
		}

		public function enqueue() {
			parent::enqueue(); // TODO: Change the autogenerated stub
			wp_enqueue_script( 'jquery-ui-sortable' );
		}

		public function custom_control_enqueue() {
			wp_enqueue_script( 'cst_customizer_control', esc_url( get_stylesheet_directory_uri() . '/assets/js/cst-customize-control.js' ), array( 'customize-controls', 'select2' ), '1.0', true );
		}
		/**
		 * Refresh the parameters passed to JavaScript via JSON.
		 *
		 * @since 3.1.0
		 * @access public
		 *
		 * @see WP_Customize_Control::to_json()
		 */
		public function to_json() {
			parent::to_json();
			$this->json['sortOrder']   = $this->sort_order;
			$this->json['id']          = $this->id;
			$this->json['description'] = $this->description;
		}

		public function content_template() {
			parent::content_template();
			?>
			<label for="{{ data.id }}" class="{{ data.banana }}">
				<# if ( data.label ) { #>
					<span class="customize-control-title">{{ data.label }}</span>
					<# } #>
						<# if ( data.description ) { #>
							<span class="description customize-control-description">{{ data.description }}</span>
							<# } #>
			</label>
			<# if ( ! data.sortOrder ) {
					return;
					} #>
				<ul id="{{ data.id }}" class="widget-area-select">

					<# for ( key in data.sortOrder ) { #>
						<li class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>{{ data.sortOrder[key] }}</li>
						<# } #>
				</ul>
			<?php
		}

		/**
		 * Render content just like a normal select control.
		 *
		 * @since 3.1.0
		 * @access public
		 */
		public function render_content() {
		}
	}
}